### ISSUE TITLE
autoamexalloffers fails with new gui and formatting

### ISSUE THREAD

**Issue by ScoobyDone** [willguxy/AutoAmex#3] opened 2017-06-12 00:07 UTC
autoamexalloffers has stopped working.  it worked fine with the old interface but now doesn't.

i think it might have something to do with how amex now displays the expiration dates - at least I don't remember seeing this output before.  amex has "enhanced" the interface to show, instead of always showing the actual date; it now displays "expires today" and "expires in 2 days" up to at least "expires in 12 days".  I don't know about "tomorrow" vs. "in 1 day" or how high this enhanced display goes - probably 14.

I can see chromedriver hit the "added to card" link and then the "view all" button and display the whole page but then it just refreshes the page, sits there for a few seconds and then goes on to the next card.

the output log contains a few blank lines and then the login name of the user on each line. 

not a python expert, so I've no idea how to fix this but am willing to test and help in any way I can.  thanks!

**Comment by willguxy** [comment] 2017-06-12 00:53
Thank you. Will fix as soon as I can.

**Comment by willguxy** [comment] 2017-07-19 05:40
@ScoobyDone Just want to follow up quickly -- I've made a few fixes and now the `autoamex.py` should work with the new GUI, though `autoamexalloffers` still needs a few tweaks.

**Comment by ScoobyDone** [comment] 2017-07-25 21:21
@willguxy  thanks for the update.  unfortunately, alloffers is what was broken for me.  but at least the update didn't break autoamex.  :)

i had a bunch of runs crash while testing so I have no way to find those dozen amazon offers scattered through way too many accounts without scraping via the alloffers script (since the logfile didn't get written post-crash).

**Comment by doggpound007** [comment] 2017-07-26 11:14
It seems to be working quite well.  An issue I have found recently (with autoamex) is that the log file shows some offers were activated for a login however in reality they were not activated.  Has anyone else reported this to you?

**Comment by willguxy** [comment] 2017-07-31 07:12
@doggpound007 did you pull the latest version? It used to be a problem but I thought it's more robust now (although could still happen). My current logic in code implementation is to 

`Add -> Refresh Page -> Try Adding Again`

This seems to be an reasonable approach. Other than this, I haven't been able to come up with any better solution

**Comment by willguxy** [comment] 2017-07-31 07:17
@ScoobyDone I apologize for the difficulty you experienced with `alloffers`.

I'll try to fix it within a month or two. I know where the problem is. shouldn't be hard, but takes a bit of digging.

Meanwhile, I would suggest using the `getOffers.sh` to scrape through the log files to find out which offer has been added to which card (if you are on Linux/Mac)

e.g. `./getOffers.sh amazon tmp/*.log`

**Comment by doggpound007** [comment] 2017-07-31 15:39
I will have to do more testing.
I did update recently but not sure exactly when.

**Comment by ScoobyDone** [comment] 2017-08-09 22:48
@willxguy

Thanks for not giving up on this.  

getoffers.sh doesn't work either (and it wouldn't in my use case since the synced offers never made it into the logfiles).  I just get loginIDs returned...

this pipeline works for newly formatted logfiles that don't print "all available offers added" or whatever, note the filename string in the initial grep.  Unoptimized but still processes my 3MB of logs in under a second.  FYI - written using GNU, not OSX.

grep -hA 1 'ID: ' tabsync_2017-08* | grep -ve '^--$' | perl -pe 's/^# [0-9]*? ID: //g' | perl -0pe 's/\nAvailable offers are: /\t/g' | sort | perl -0pE 'while(s/^((.+?)\t.*)\n\2\t/$1, /gm){}'

explained:
grep -hA1 ~ no filenames and 1 line after matching 'ID: '
grep -ve ~ strip out the "--" that -A adds in previous grep
1st perl ~ strip out the "# xx ID: " string
2nd perl ~ strip out the newline and other text, replacing with a tab which sets up the 3rd perl
sort the file so the following perl will work
concatenate the lines that begin with the same first field

**Comment by Serion717** [comment] 2017-09-20 18:08
@willguxy Hi. First thanks for AutoAmex!  In a future enhancement, could you update the code to include the expiration date in the logs?  That would be SUPER helpful.

**Comment by willguxy** [comment] 2017-12-04 01:13
fixed.
closing for now. feel free to re-open if anything

**Closed as completed by willguxy** 2017-12-04 01:13 UTC
